### ISSUE TITLE
Wireless and Wired USB keyboard issue

### ISSUE THREAD

**Issue by usenethound** [GideonZ/1541ultimate#159] opened 2020-06-22 21:18 UTC
With the new 1.34 firmware I am having an issue with my wireless keyboard. In any of the Ultimate64 menus, when I hit any of the direction arrows, it processes it as 2 key-presses. The same happens when say I create a new .d64 disk image from the Ultimate menu. When I go to name the disk, say if I want to call it SAVE, on the screen it actually types SSAAVVEE ... Turbo mode is off...

Thanks!

**Comment by usenethound** [comment] 2020-06-22 21:19
It makes things like switching from PAL to NTSC impossible with just the wireless USB keyboard alone because there are only 2 options so the arrow always brings you back to whatever option you were on. To get around this I have been using the joystick in the Ultimate menus but that also became an issue when I used the swap joystick port option in the menus because a game required the joystick to be on port 1. Once I did this, I could play the game but I could not set the swap joystick option back to NORMAL again because I couldn't use the joystick in the Ultimate menus anymore since I swapped it. I had to reset the settings to defaults and set everything up again.

**Comment by tehashen** [comment] 2020-06-23 09:23
I’ve the same issue with an wired USB keyboard.

**Comment by usenethound** [comment] 2020-06-23 11:56
tehashen, thanks for the confirmation of the issue also using wired USB. I'll edit the topic to reflect...

**Comment by Jumpman64** [comment] 2020-06-29 14:54
Not exactly the same problem and it exists in fw 1.28 too but a wireless Rapoo K2600 keyboard with touchpad locks up the C64 keyboard when pressing FN (to get the F-keys) or Shift and Ctrl. If pressing these keys a few times the effect goes away, but switching between keyboards or simultaneous use isn't really possible with that strange behavoir.

**Comment by p2mate** [comment] 2020-07-04 17:15
I have the same problem, however it only happens when interface type is set to Freeze. When I set interface type to overlay on HDMI, keys works as expected, even when the interface overlay is not displayed.

**Comment by GideonZ** [comment] 2020-07-04 18:17
This is very helpful information! Thank you.  I could not reproduce, and
now I at least know why. I don't use the Freeze menu.

**Comment by p2mate** [comment] 2020-07-04 19:09
Another piece of information: the 'double key' effect only happens when using the separate arrow keys. Using shift + a numpad arrow key, works as expected.

**Comment by mlukasek** [comment] 2020-08-30 22:26
My both wired an wireless USB keyboards to the same. Overlay on HDMI helps, but only if you use HDMI ;-)
I found you can use Ctrl + left arrow to move DOWN, Ctrl + down arrow to move UP, Ctrl + right arrow is LEFT, and Ctrl + Enter does normal single ENTER ;-) But it is crazy.

**Comment by p2mate** [comment] 2021-01-09 16:00
At least for me this is fixed in 1.37

**Closed** 2021-07-26 13:43 UTC
