### ISSUE TITLE
CRT compatibility

### ISSUE THREAD

**Issue by Flexmaen** [GideonZ/1541ultimate#56] opened 2019-01-27 19:58 UTC
I came across some CRT images that did work on the Vice Emulator, but did not work with the 1541 Ultimate 2. I tried on both C128 and C64 with the nms settings that usually work.

Here is one of these images for example.
[alieninfilt1.zip](https://github.com/GideonZ/1541ultimate/files/2800461/alieninfilt1.zip)

**Comment by GideonZ** [comment] 2019-02-08 08:12
This comment sounds like the Ultimate should do what VICE does, ...  Is this realistic? The Ultimate is a hardware 'emulator', not a software emulator. It is likely that I need to add hardware modules to support this CRT. What is the type of this CRT? Does the Ultimate tell you what type it is, and that it is not supported?

**Comment by markusC64** [comment] 2019-02-08 08:41
Please tell us more what is not working. I can start that crt successfully on my U2, U2+ and on my U64.

Note: Have to turn off comflicting emulations such that REU, Ultimate DOS & Ultimate Audio, of cause.

**Comment by markusC64** [comment] 2019-02-08 08:41
@Gideon: That CRT is of type EasyFlash...

**Comment by Flexmaen** [comment] 2019-02-09 14:44
I never said that 1541-U should do, what Vice does. But since this CRT did not work on my 1541-U2, I did use Vice to confirm that this is a valid CRT.

I just get a scrambeld screen, similar to [this](https://www.breadbox64.com/wp-content/uploads/2015/11/IMG_4533.jpg). I did try this on both my C128 and C64, and did turn everything off (Cartrdige, REU, Ultimate DOS).

**Comment by marty41** [comment] 2019-02-09 20:24
The attached Easyflash crt does work properly on my U2+, U2 and also on my U64. I just tested it 30 mins ago on my hardware. No problem at all.
So I think it might depend on your configuration and it seems it isn't a common issue.

**Comment by markusC64** [comment] 2019-02-09 20:43
Another possibility is that your U2 has a firmware that is too old.

**Comment by Flexmaen** [comment] 2019-02-10 19:02
I'm using Firmware 3.2 and didn't find any newer release.

Well, even if it's not a common issue I'll try to narrow down the reasons why this happens.

**Comment by Flexmaen** [comment] 2019-02-13 21:07
Ok, i did try 3.4ß, and now this one works.
Compatibility is far better, although some images still show a black screen on my C128, like this one:
[warmup.zip](https://github.com/GideonZ/1541ultimate/files/2862204/warmup.zip)

Btw, I think it'd be a great idea to put the current builds somewhere where you'll expect it, like here on github or on the homepage. Is there a reason why they cannot be found there yet?

**Comment by Grrrolf** [comment] 2019-02-13 21:23
Not sure from whom you've got a 3.4 beta version, but official releases by Gideon can be found on [1541ultimate.net](http://www.1541ultimate.net/content/index.php?option=com_content&view=category&id=4&layout=blog&Itemid=19) for the U2/U2+ carts (and in the facebook group). Official U64 releases can be found on [ultimate64.com](https://ultimate64.com/Firmware) and also in the facebook group.

For myself I have created [this overview of firmware releases](https://ammo.home.xs4all.nl/Ultimate_Carts/firmware_ultimate_carts.html).

**Comment by markusC64** [comment] 2019-02-13 21:25
Well, because of network poblems, Gideon did not make official releases for the U2 for some time. That explains that you do not find newer official U2 releases.
Anyway, the public sources can be used to build U2 versions.

**Comment by GideonZ** [comment] 2019-02-13 21:33
I would strongly advice not to.  One could brick the U2, and I do not
intend to cover that under warranty when people build their own firmwares,
especially non-tagged ones.

The last days I have been trying to find the problem with the U2. I once
again found one compiler bug with SDK 2016.2. A function that would return
either 0 or -1 on error, returned an address instead. It turned out that
the optimizer had optimized out the return value. Yey.

--> I am THIS close to throwing out the Xilinx trash out of the window. If
one can't depend on the compiler, then what to do? <--

However, something else fishy is going on in the tcpip_thread. At times it
just hangs there. Since I do not have any decent debug facilities for the
Xilinx part, I am now trying to reproduce this on the Altera part, using
the Nios processor to bootstrap the Microblaze from Eclipse. Hopefully I'll
be able to find the problem using SignalTap. Hopefully the rest of the
hardware is compatible enough to find the bug.

**Comment by Flexmaen** [comment] 2019-02-14 10:27
Ok, 3.2 was the last official version I found on the Homepage. And that is the one that has the problems I mentioned. Since 3.4ß did better this shows that this is not a problem with my settings.
I wonder which version the people are using that seem to have no problems at all with CRT-files.

@GideonZ Good luck with your compiler, sounds like an annoying problem. :(

**Comment by GideonZ** [comment] 2019-02-23 12:36
> Ok, i did try 3.4ß, and now this one works.
So I can close it.

**Closed by GideonZ** 2019-02-23 12:36 UTC
