### ISSUE TITLE
U64 V1.34-3.8: Random loading hang-ups using SpeedDOS+ v2.7

### ISSUE THREAD

**Issue by Jumpman64** [GideonZ/1541ultimate#160] opened 2020-06-23 10:40 UTC
If a program loads data the drive hangs up while loading all of a sudden.
This occured the first time under U64 rev1.2 V1.33 in my BASIC prg that loads a picture to charset via kernal load. The half loaded data looks damaged (horizontal lines in the hair) and the drive LED stays on. (see attached picture)
![garbeledload](https://user-images.githubusercontent.com/50739888/85391990-3388cf00-b54b-11ea-9f0d-ee5f9920f7ce.jpg)
should look like this
![ripley](https://user-images.githubusercontent.com/50739888/85393496-659b3080-b54d-11ea-9476-ce503addd408.png)

So far it seems that it just happens under SpeedDOS after less than a minute or longer.
Tried dolphindos, jiffy and kcs for a while and they seem unaffected.
It didn't happen in an emulator using SpeedDOS either.
I flashed back to V1.28 - 3.7 and my loadstress2 ran perfect for over one hour.
So it looks like something changed to the bad for SpeedDOS in the actual fw 1.34 (since 1.33).

You can provoke the fault by continous loading. Let the Koala-Show run for a while until you get some partly garbeled graphics on the upper the screen and the floppy LED stays on. (D64 and roms attached)
[U64_loadtest.zip](https://github.com/GideonZ/1541ultimate/files/4818713/U64_loadtest.zip)

And here's my little prg running a loading loop. it's maybe quicker and more convenient to produce the loading fault.
[loadstress2.2.zip](https://github.com/GideonZ/1541ultimate/files/4830300/loadstress2.2.zip)
(updated on 25.6.: ti$ didn't work, included cycle count instead)

I always reset the config when updating the firmware (from 1.28 to 1.33 and 1.33 to 1.34).

Updated to 1.34 and the load fault still happens.

**Comment by Jumpman64** [comment] 2020-06-23 12:59
...here's my little prg running a loading loop. it's maybe quicker to produce this loading fault.
[loadstress2.zip](https://github.com/GideonZ/1541ultimate/files/4819515/loadstress2.zip)

**Comment by Jumpman64** [comment] 2020-06-23 14:39
I flashed back to V1.28 - 3.7 and my loadstress2 is running perfect for over one hour now.
So it looks like something changed for SpeedDOS (and maybe other fastloaders) in the actual fw 1.34.

**Comment by GideonZ** [comment] 2020-06-26 20:34
Was able to reproduce with 1.34. Reverted one change from the contribution of gyurco to the 6522 VIA code (committed on May 11). The koala slideshow has now been running for some minutes now. If this was the fault, it will be fixed in the next version (1.35).

**Comment by GideonZ** [comment] 2020-06-26 21:56
It has been running now for well over an hour without any issues. I consider it fixed.

**Comment by Jumpman64** [comment] 2020-12-06 10:26
The problem still exists in v1.37

**Comment by Jumpman64** [comment] 2020-12-06 10:33
@GideonZ  Please use the attached test programm, it leads to the problem more quickly.
Hope you don't mind that i converted your logo to the beloved computer where it belongs. :)
[kernalloadstresstest.zip](https://github.com/GideonZ/1541ultimate/files/5648599/kernalloadstresstest.zip)

**Comment by Jumpman64** [comment] 2020-12-06 10:41
Looks like this when the loading got stuck:
![loadmessedup](https://user-images.githubusercontent.com/50739888/101277874-bf1fb080-37b7-11eb-83b7-730cb3362aea.jpg)

**Comment by Jumpman64** [comment] 2021-05-12 15:55
@GideonZ Since last year i think about buying the U64 UserPort Adapter but this problem made me hesitate (still). I guess it's likely that this problem occurs with a real 1541 SpeedDOS drive too. Can you give hope that the cause can be found and fixed in the near future?
Bij voorbaat bedankt

**Comment by GideonZ** [comment] 2021-05-12 16:23
Giving false hope is worse than not giving hope. Not saying it cannot be
solved, but I am saying that it needs to be investigated. I don't know yet
if it is fully fixable, due to some timings being dictated by the
electronics around the FPGA. It's not all internal. Oh... for the internal
drive it is, but for an external device it may not be so.

**Comment by GideonZ** [comment] 2021-05-20 13:39
@Jumpman64 I think I finally found the problem. It was a very nasty thing to find. As you would probably know, the transfer between the drive and the host uses handshaking. For data transfers to the drive, the PC output of the 6526 causes a trigger on the CB1 input of the 6522 in the drive. Vice versa, on data transfers from the drive, the CA2 output of the 6522 causes a trigger through the FLAG# input of the 6526.

To make it a bit more interesting, the CB1 and CA2 pins of the CIA are bidirectional (while the PC / FLAG pins on the 6526 are not). Inside of the FPGA, signals are always unidirectional, so logical pins usually consist of three signals; the output signal, the tristate signal and the input signal. When you want to know the logic level of a pin, both output and tristate levels need to be considered. Usually, when an output is disabled, the signal is 'high', when no one else is driving it.  Well, that's what the emulation of NMOS would do, where inputs read as '1'.

Now the interesting part.... For some reason, the speeddos kernal switches direction of the CA2 pin. Multiple bits in the PCR register change at once. Due to timing delay differences in the out and tristate signal, the logic gate that determines the actual level of the signal glitches low for a very small amount of time. Not sure how much, but let's say a nano-second. In synchronous systems, this is not a problem, as the signal will be stable before the next clock edge. However, the receiving end (6526) runs off a different clock, asynchronous to the clock the 6522 uses. So when this glitch happens around the clock edge of the 6526, a falling edge on FLAG is observed, and the status bit in ISR ($DD0D) is set accordingly. This fucks things up quite badly, as the host and the drive are now out of sync.

The problem was solved by requiring the FLAG input to be low for at least two consequitive cycles (~ 40 ns). This provides enough filtering for the glitch. Another solution might be a change in the 6522, which makes the output signal '1' at any time the pin is set to input. This will eliminate the glitch. In addition, the tristate signal does not need to be considered anymore either.

**Comment by Jumpman64** [comment] 2021-05-20 15:53
Awesome²! I guess that's why they named these little buggers "complex" and "versatile". 😆 Now i'm really keen on the next unofficial fw to test things out. You've already brought the Userport adapter on the way to me so more floppy torture is on the schedule. Big thanks!

**Closed** 2022-03-19 13:39 UTC
