### ISSUE TITLE
1.37 - 3.9a U64, Ulticopy Directory list duplication

### ISSUE THREAD

**Issue by QuillOmega0** [GideonZ/1541ultimate#228] opened 2021-06-20 20:32 UTC
Intermittently I've seen cases where Ulticopy starts saving the copy of the directory list from a previous copy to recently copied floppies after quitting out and reopening it and starting a new copy process. Restarting the U64 resolves this.

**Comment by Grrrolf** [comment] 2021-06-20 20:56
I have not been able to reproduce this issue. Everything works as expected on my set-up. Could it be that your source disk drive does not notice that the disk has changed?

**Comment by QuillOmega0** [comment] 2021-06-20 23:53
> I have not been able to reproduce this issue. Everything works as expected on my set-up. Could it be that your source disk drive does not notice that the disk has changed?

I suspect that Ulticopy would reinit the drive and clear the BAM and Directory prior to doing the drive ip.

This is an extremely difficult issue as it's intermittent and has no rhyme and reason. 

But this is what I'm seeing https://imgur.com/a/u7dJzYt

This is on the latest beta image.

**Comment by Grrrolf** [comment] 2021-07-06 21:07
### **I tested this on an ultimate64**
It's a bit weird. I transferred two disks. Both have a different disk name / label. One ends with s1a and the other with s2a. I have enabled 'ulticopy uses disk name'. However, it suggests to use the disk name of the s1a disk and not the s2a disk.

This means that the test I did today, now shows the same behaviour as you described.

How to reproduce:
* have ulticopy uses disk name enabled
* transfer first disk using Ulticopy8
* save the file with the suggested name
* transfer another disk
* now ulticopy suggest the same file name as before
* give it another name (I added a - as suffix)
* check the disk name / label. It's different from the suggested file name.

When using the U64, a 'reboot' doesn't solve this issue.
A cold boot solves this issue, but only for the first disk being transferred.

I cannot reproduce what you show in the screenshots.

**Comment by GideonZ** [comment] 2021-07-11 09:57
The issue was that the underlying binary image of the disk was not updated. Although not thoroughly tested, this should now have been fixed. We can reopen this ticket if it turns out to be not working still.

**Closed by GideonZ** 2021-07-11 09:57 UTC
