### ISSUE TITLE
U64 capture save to tape error

### ISSUE THREAD

**Issue by RichardTND** [GideonZ/1541ultimate#67] opened 2019-03-17 09:37 UTC
On the current U64 firmware build (V1.10 Official 3.4) the Ultimate 64's 'Capture Save to Tape' option tries to capture a save to .tap image, but after finishing saving, and refreshing the directory. A 20kb .tap image is made, which is incomplete. There's probably a bug in this area.

**Comment by GideonZ** [comment] 2019-04-20 20:13
The file created was actually 20 bytes, not 20 kB.  Fixed. Root cause: the sense line was not correctly considered. Fixed in public release 1.18.

**Closed by GideonZ** 2019-04-20 20:13 UTC
