### ISSUE TITLE
Batteries Included 80 column display does not work with firmware U64 3.8 

### ISSUE THREAD

**Issue by kinshi** [GideonZ/1541ultimate#154] opened 2020-06-18 16:44 UTC
80 col display from the BI-80 is a full screen of garbled characters with turbo enabled or disabled. (1.33)

Revert to 1.28 and the BI-80 works as expected.

**Comment by kinshi** [comment] 2020-06-22 01:55
Tested with 1.34, problem persists. Unit works as expected with firmware rev 1.28

**Comment by GideonZ** [comment] 2020-06-26 19:04
Could you please attach the binary that you are using? This simplifies reproducing and testing it.

**Comment by kinshi** [comment] 2020-06-27 06:31
There is no binary program associated with this action...

What occurs happens simply as result of activating the 80-column display via SYS 33000. When engaged, the 80-column output is a solid screenful of random characters (not unlike what occurs on PET systems when the CPU is defective, and the BI-80 uses the same CRTC they do)

http://mikenaberezny.com/wp-content/uploads/2008/04/bi80-manual.pdf

Appendix A , Page A-1 has the memory ranges it uses and theory of operation

U64 Config:

REU off
No carts loaded
Turbo disabled
JiffyDOS 6.0x alternate kernel loaded

Note about the BI80 - It has BASIC 4.0 in ROM that is engaged automatically (cannot be disabled prior to boot)

**Comment by GideonZ** [comment] 2020-06-27 08:36
Ah!  It's a cartridge...   Maybe I should have googled it to know. :-D

I see in the manual that the cartridge 'snoops' writes in the area
$9800-$9FFF:

[image: image.png]

For this case, the cartridge "Bus Operation Mode" should be set to "Writes".
I hope that this solves the problem. Can you confirm?

**Comment by GideonZ** [comment] 2020-06-27 08:40
Ah!  It's a cartridge...   Maybe I should have googled it to know. :-D

I see in the manual that the cartridge 'snoops' writes in the area
$9800-$9FFF:

![image](https://user-images.githubusercontent.com/11030985/85918387-a1423d00-b862-11ea-94fc-2f3555b20b92.png)

For this case, the cartridge "Bus Operation Mode" should be set to "Writes".
I hope that this solves the problem. Can you confirm?

**Comment by Grrrolf** [comment] 2020-06-27 12:04
The cartridge also contains a crt controller chip which comes. The one in the BI-80 seems to run at 2.5Mhz . 

![image](https://user-images.githubusercontent.com/10052794/85921696-3e5e9f00-b87e-11ea-9ff1-d45335a9f5e1.png)

Spec sheet for the crt controller chip: https://datasheetspdf.com/pdf-file/512965/Rockwell/R6545/1

Would it be likely it gives garbled output in turbo mode because it can't keep up with the C64 anymore? I remember this when my dad had his spectravideo upgraded to make it much faster. As a result the 80 columns controller card needed a modification to keep up with the spectravideo computer itself.  Without the modification for the 80 columns controller card switched on, it gave nothing but garbled text.

**Comment by kinshi** [comment] 2020-06-28 01:10
"For this case, the cartridge "Bus Operation Mode" should be set to "Writes".
I hope that this solves the problem. Can you confirm?"

Confirmed, this indeed solved the issue. Cartridge initializes 80-col display properly using SYS33000

Further notes...the cartridge will function in "Turbo" mode at 2mhz, but fails with clock speeds of 3Mhz and up. 2Mhz however is still pretty sweet when using this card.

**Comment by GideonZ** [comment] 2020-06-29 21:09
Great, then for now I'll close this issue. I am not sure why it won't run at frequencies above 2 MHz though. It should!

**Closed by GideonZ** 2020-06-29 21:09 UTC
